#默认使用配置
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.1.220:3309/webapi?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: apiuser
    password: Ctm56@Long
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    #连接池初始化连接数量
    initialSize: 1
    #最小空闲数
    minIdle: 3
    #连接池最大活跃连接数
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #连接是否有效的查询语句
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandoned: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # SQL监控后台登录用户名
    druidLoginName: admin
    # SQL监控后台登录用户密码
    druidPassword: admin

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.example.springboot.model
  mapperLocations: classpath:mapping/*.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql



